---
- name: setup bastion host ec2
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup vars
      include_vars: vars/bastion_setup
    - name:
      include_vars: vars/output_vars
    - name: create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out
    - name: save provate-key into file bastion-key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed
    - name: create sec grp
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out
    - name: creating baston host
      ec2_key:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        group_id: "{{ BastionSG_out.group_id }}"
      register: bastionHost_out
